### DISCUSSION TITLE
Renaming tags in unions

### DISCUSSION THREAD

**Discussion by ejpcmac** [yukinarit/pyserde#442] [Q&A]
Hello, is there any way to rename a tag?

Let’s say I have this YAML file, featuring a serialised `something` that can be either `local` or `distant`, internally tagged:

```yaml
something:
    type: local # or distant
    # other fields
```

Let’s say I had this in Rust with serde, which successfully allows to deserialise the file into a `Config`:

```rust
#[derive(Debug, Deserialize)]
struct Config {
    something: Something,
}

#[derive(Debug, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
enum Something {
    Local(SomethingLocal),
    Distant(SomethingDistant),
}

#[derive(Debug, Deserialize)]
struct SomethingLocal { ... }

#[derive(Debug, Deserialize)]
struct SomethingDistant { ... }
```

Now, the closest I’ve found in Python is to write this:

```python
@dataclass
class SomethingLocal:
    # ...

@dataclass
class SomethingDistant:
    # ...

@serde(tagging=InternalTagging("type"))
@dataclass
class Config:
    something: Union[SomethingLocal, SomethingDistant]
```

But this means I need to have a YAML file like this instead:

```yaml
something:
    type: SomethingLocal # or SomethingDistant
    # other fields
```

As there is no such thing as an enum with fields in Python, I don’t see how to properly name the variants. Is there anyway with `pyserde`?
