### ISSUE TITLE
Support Union

### ISSUE THREAD

**Issue by yukinarit** [yukinarit/pyserde#1]
To read this toml with pyserde,

```toml
[packages]
pyserde = { path = "../", editable = true }
toml = { version = "*" }
requests = "*"
```
I define the pyserde classes like this.
It's nice `packages` can be `Union` which is `str` or `Package` object.

```python
@deserialize
@dataclass
class Package:
    path: Optional[str] = None
    version: Optional[str] = None
    editable: bool = False

@deserialize
@dataclass
class Pipfile:
    source: List[Source]
    requires: Requires
    packages: Dict[str, Union[str, Package]]
```
