### ISSUE TITLE
Mapping to correct class in union type

### ISSUE THREAD

**Issue by bernardomig** [yukinarit/pyserde#150]
Hi, I am using your pyserde to deserialize configuration files. I have multiple classes that are mapped based on a field, and I do not know how to customize pyserde to correctly serialize/deserialize my union type.

Check the example: 

```yaml
apiVersion: v1beta
...
spec:
  pipeline:
    input:
      operation: read
      pattern: ^DE\-PH\-PL_[A-Z]{3}[0-9]{9}_[0-9]{2}\-[0-9]+\-.+\-.+.pdf
      type: pdf
    output:
      operation: copy
      from: input
      filename: |
        REPLACE(DE/PH/{AS_INPUT}.pdf, "DE-PH-", "")
```

I have the following dataclasses in my code:

```py
@deserialize
@serialize
@dataclass
class ReadOperation:
    pattern: str
    type: str
    properties: Dict[str, str]


@deserialize
@serialize
@dataclass
class CopyOperation:
    filename: str
    from_: str = field(metadata={'serde_rename': 'from'})

...


@deserialize
@serialize
@dataclass
class Spec:
    pipeline: Dict[str, Union[CopyOperation, ReadOperation]]
```

How can I deserialize, based on the field `operation` in the YAML file?
